---
- name: Kubernetes Master

  hosts: master
  remote_user: pi
  become: true

  roles:
  - role: kubernetes
    mode: master
    # "master" must be an IP, otherwise flannel will core dump:
    master: 192.168.23.200

- name: Kubernetes Nodes

  hosts: nodes
  remote_user: pi
  become: true

  roles:
  - role: kubernetes
    mode: node
    master: 192.168.23.200
