---
- name: Kubernetes Master

  hosts: master
  remote_user: pi
  become: true

  roles:
  - etcd
  - role: flannel
    mode: master
  - docker
  - role: kubernetes
    mode: master

- name: Kubernetes Nodes

  hosts: nodes
  remote_user: pi
  become: true

  roles:
  - role: flannel
    mode: node
  - docker
  - role: kubernetes
    mode: node
