- name: Install own docker service
  template: src=docker.service dest=/lib/systemd/system/docker.service owner=root group=root mode=0644

- name: Enable and restart docker service
  service: name=docker enabled=true state=started
