---
- name: Configure WiFi
  template: src=wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

- name: Add hosts
  template: src=hosts dest=/etc/hosts

- name: Set hostname
  hostname: name="{{ name }}"

- name: Restart hostname
  service: name=hostname state=restarted
  async: 45
  poll: 0

- name: Set user password
  user: name=pi password="{{ user.password }}"

- name: Switch off power management for WiFi
  lineinfile: dest=/etc/network/interfaces state=present line="wireless-power off" insertafter="^iface wlan0"

- name: Verify ~/.ssh
  file: path="/home/pi/.ssh" state=directory recurse=no owner=pi group=pi

- name: Copy SSH Key
  copy: src=~/.ssh/id_dsa.pub dest=/home/pi/.ssh/authorized_keys mode=0600 owner=pi group=pi

- name: Upgrade APT to the lastest packages
  apt: upgrade=safe

- name: Install hdparm and iperf
  apt: name='{{ item }}' force=yes state=present
  with_items:
    - hdparm
    - iperf
